# docker-compose file
version: '3'

services:
  discoveryserver:
    image: amazoncorretto:11
    container_name: discoveryserver
    volumes:
      - ./apps/discoveryserver:/app
    working_dir: /app
    ports:
      - "8761:8761"
    command: ./gradlew bootRun
    environment:
      - server.port=8761
      - eureka.instance.hostname=discoveryserver
      - eureka.client.serviceUrl.defaultZone=http://discoveryserver:8761/eureka/
    networks:
      - cineplex-network

  moviecatalog:
    image: amazoncorretto:11
    container_name: moviecatalog
    volumes:
      - ./apps/moviecatalog:/app
    working_dir: /app
    command: ./gradlew bootRun
    ports:
      - "8080:8080"
    environment:
      - server.port=8080
      - eureka.instance.hostname=discoveryserver
      - eureka.client.serviceUrl.defaultZone=http://discoveryserver:8761/eureka/
    depends_on:
      - discoveryserver
    networks:
      - cineplex-network
  
  movieinfo:
    image: amazoncorretto:11
    container_name: movieinfo
    volumes:
      - ./apps/movieinfo:/app
    working_dir: /app
    command: ./gradlew bootRun
    environment:
      - server.port=8080
      - eureka.instance.hostname=discoveryserver
      - eureka.client.serviceUrl.defaultZone=http://discoveryserver:8761/eureka/
    depends_on:
      - discoveryserver
    networks:
      - cineplex-network
  
  movieratings:
    image: amazoncorretto:11
    container_name: movieratings
    volumes:
      - ./apps/movieratings:/app
    working_dir: /app
    command: ./gradlew bootRun
    environment:
      - server.port=8080
      - eureka.instance.hostname=discoveryserver
      - eureka.client.serviceUrl.defaultZone=http://discoveryserver:8761/eureka/
    depends_on:
      - discoveryserver
    networks:
      - cineplex-network
    
networks:
  cineplex-network:
    driver: bridge