server:
  port: 8083

spring:
  application:
    name: movie-ratings

eureka:
  instance:
    hostname: ${spring.application.name}-peer-${random.value}
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}-${random.value}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
  client:
    eureka-service-url-poll-interval-seconds: 10
    registry-fetch-interval-seconds: 10