server:
  port: 8083

spring:
  application:
    name: movie-ratings

eureka:
  instance:
    hostname: ${spring.application.name}-peer-${random.value}
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}-${random.value}
    prefer-ip-address: true
    status-page-url-path: /swagger-ui/index.html